In [1]:
import numpy as np

DataTypes and Attributes

In [2]:
#numpy main datatype is  ndaaary
a1 =np.array([1,2,3])
a1 

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 =np.array([[1,2,3],[3,4.3,5.5]])
a2 

array([[1. , 2. , 3. ],
       [3. , 4.3, 5.5]])

In [5]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,12],
              [13,14,15],
              [16,17,18]]])
a3 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a3.shape

(2, 3, 3)

In [7]:
a3.ndim

3

In [8]:
a3.size

18

# Create a DataFrame From a Numpy array

In [9]:
import pandas as pd

df = pd.DataFrame(a2)
df


0    1    2
0  1.0  2.0  3.0
1  3.0  4.3  5.5

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a3a = pd.DataFrame(a1)
a3a

0
0  1
1  2
2  3

# 2. Creating 

In [12]:
sample_array= np.array([1,2,3])
sample_array

array([1, 2, 3])

In [13]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# range array
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

Random array

In [15]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[2, 8, 6, 6, 0],
       [5, 5, 1, 6, 3],
       [1, 5, 0, 5, 9]])

In [16]:
random_array.size

15

In [17]:
random_array.shape

(3, 5)

In [18]:
random_array_1 = np.random.random((3,4))
random_array_1

array([[0.74201476, 0.15612695, 0.44792148, 0.2609076 ],
       [0.66372154, 0.41547825, 0.3932726 , 0.67456724],
       [0.77800897, 0.20258522, 0.1722632 , 0.61128419]])

In [19]:
random_Array_2 = np.random.rand(2,3)

In [20]:
random_Array_2

array([[0.48577538, 0.61208698, 0.35577542],
       [0.71532954, 0.20339245, 0.26066447]])

Pseudo- Random numbers

In [21]:
np.random.seed(0)
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

# 3. Viewing Arrays and Matrics 

In [22]:
# fining unique numbers 

np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a1 
a2 
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [24]:
a1

array([1, 2, 3])

In [25]:
a2

array([[1. , 2. , 3. ],
       [3. , 4.3, 5.5]])

In [26]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [27]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [28]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [29]:
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

## Manipulating and comparing array

### Arithemic

In [30]:
a1 

array([1, 2, 3])

In [31]:
ones = np.ones(3)

In [32]:
ones

array([1., 1., 1.])

In [33]:
a1 + ones

array([2., 3., 4.])

In [34]:
a1 * ones

array([1., 2., 3.])

In [35]:
zeros =np.zeros(3)

In [36]:
zeros

array([0., 0., 0.])

In [37]:
a1 * zeros

array([0., 0., 0.])

In [38]:
a1

array([1, 2, 3])

In [39]:
a2 / a1

array([[1.        , 1.        , 1.        ],
       [3.        , 2.15      , 1.83333333]])

In [40]:
# floor division removes the decimal (rounds down)

In [41]:
a2 // a1

array([[1., 1., 1.],
       [3., 2., 1.]])

In [42]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [43]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

##  Aggregation

### Aggeration = performing the same operation on number of things



In [44]:
listy_list = [1,2,3]
type(listy_list)


list

In [45]:
listy_list

[1, 2, 3]

In [46]:
sum(listy_list)

6

In [47]:
np.sum(a3)

171

### Use Pyton's methods (sum()) on Python datatypes and use Numpy's Methods on Numpy arrays (n.sum())

In [48]:
# create a massive array

massive_array = np.random.random(10000)
massive_array.size

10000

In [49]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) #Numpy's np.sum()

5.62 ms ± 449 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
34.8 µs ± 649 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [50]:
np.mean(a2)

3.1333333333333333

In [51]:
# Standerd daviation = a measure of how spread out a group of number is from mean 

np.std(a2)

1.4624940645653537

In [52]:
#Variance  = measure of the average degree ti which each number is diiferent to the  mean
# Higter variance = wider range of number
# Lower Variance = lower range on number

np.var(a2)

2.138888888888889

In [53]:
np.var(a3)

26.916666666666668

In [54]:
#standard deviation = square root of variance
np.sqrt(np.var(a2))

1.4624940645653537

 ### Reshapping and transposing

In [55]:
a2

array([[1. , 2. , 3. ],
       [3. , 4.3, 5.5]])

In [56]:
a2.shape

(2, 3)

In [57]:
a3, a3.shape

(array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],
 
        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]]),
 (2, 3, 3))

In [58]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

array([[[1. ],
        [2. ],
        [3. ]],

       [[3. ],
        [4.3],
        [5.5]]])

In [59]:
a2_reshape.shape

(2, 3, 1)

In [60]:
a3.shape

(2, 3, 3)

In [61]:
a2_reshape * a3

array([[[ 1. ,  2. ,  3. ],
        [ 8. , 10. , 12. ],
        [21. , 24. , 27. ]],

       [[30. , 33. , 36. ],
        [55.9, 60.2, 64.5],
        [88. , 93.5, 99. ]]])

In [62]:
#transposing
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

## Dot Product

In [63]:
np.random.seed(0)

mat1 = np.random.randint(10, size =(5,3))
mat2 = np.random.randint(10, size = (5,3))

mat1 

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [64]:
 mat3 = np.dot(mat1, mat2.T)

In [65]:
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

  ## Dot Product Example (Nut Butter sales)

In [66]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size = (5,3))

sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

### Create weeekly_Sales dataFrame

In [67]:
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon","Tru","Wed","Thrus","Fri"],
                           columns=["Almond Butter", "Peanut Butter", "Cashu Butter"])
weekly_sales

Almond Butter  Peanut Butter  Cashu Butter
Mon               12             15             0
Tru                3              3             7
Wed                9             19            18
Thrus              4              6            12
Fri                1              6             7

In [68]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [69]:
butter_prices = pd.DataFrame(prices.reshape(1,3),
                     index = ["Price"],
                     columns = ["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [70]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [71]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [72]:
weekly_sales

Almond Butter  Peanut Butter  Cashu Butter
Mon               12             15             0
Tru                3              3             7
Wed                9             19            18
Thrus              4              6            12
Fri                1              6             7

In [73]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [74]:
weekly_sales.T.shape

(3, 5)

In [75]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

ValueError: matrices are not aligned

## Sorting Arrays


In [77]:
random_array = np.random.randint(10, size = (3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [78]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [79]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [80]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [82]:
np.argmin(a1)

0

In [83]:
np.argmax(a1)

2

## Practical Example -NumPy in Action!!

In [95]:
# turn image into numpy array
from matplotlib.image import imread

panda = imread("numpy-images/panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [97]:
car = imread("numpy-images/car-photo.png")

In [98]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352